### ISSUE TITLE
Arreglar tu tablero (undefined pags y undefined chars)

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#121]
![image](https://github.com/alexay7/tfg/assets/119679067/aa0ab301-bdbd-4b3f-8d83-d358ce7e782c)
Al parecer esto pasa al darle pausar serie a dos series rapidamente.

**Comment by Pedrubik2000** [comment]
Mejor dicho seguidamente (sin esperar a que la serie desaparezca de tu tablero).

**Comment by alexay7** [comment]
Duplicado de #112
