### ISSUE TITLE
Bug: Al finalizar un tomo no se marca como leído 

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#13]
Buenas tardes,

al finalizar un tomo y volver al listado general, no aparece como "Leído". 
Además, al volver a acceder al mismo, no se abre la última página si no que se abre la siguiente (inexistente) y ya no se puede volver atrás.

Adjunto video al respecto.

https://github.com/alexay7/tfg/assets/102191690/02503db2-3409-467f-9433-b4014a071297

Gracias por la labor.
Un saludo.

**Comment by alexay7** [comment]
Arreglado en c8511e7ff20b47ce2c04d5ec5312732ae32d8693
