### ISSUE TITLE
(Navegador móvil) Funcionamiento erróneo diccionario

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#14]
Buenos días,

el diccionario funciona incorrectamente en navegadores móviles. Dando "un toque" sobre la palabra, este no muestra nada.
Seleccionando el texto, que por cierto solo es posible antes de que aparezca el texto de OCR, tampoco muestra nada el diccionario.

Adjunto video al respecto

https://github.com/alexay7/tfg/assets/102191690/fc110e42-6224-4d8f-8694-3d3efef6e619

¿Podría revisarlo, por favor?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Arreglado en 0806b4b0d6b5dd69bba8cfd732da684304ff4288
