### ISSUE TITLE
Tener una indicacion de error en un volumen en series

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#156]
Si la velocidad es mayor que 40 mil caracteres por hora o 50 mil. Que haya una indicacion roja en el volumen.
![image](https://github.com/alexay7/tfg/assets/119679067/348e0d5e-e93c-4967-a6ac-03b0b7ea1795)
![image](https://github.com/alexay7/tfg/assets/119679067/a881dff3-26bd-48f7-8d53-0889fd2e54f8)

**Comment by alexay7** [comment]
Con qué motivo?
