### ISSUE TITLE
Sugerencia: Mejorar copiado de texto.

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#167]
Buenas tardes,

cuando selecciono todo el texto de un bocadillo y lo copio para luego pegarlo en páginas de traducción online como DeepL, el texto copiado incluye los retornos de carro tal y como aparecen en el bocadillo, viendote obligado como usuario a eliminarlos uno por uno para que la traducción sea correcta y coherente.

Copiando desde el panel lateral, el problema es el mismo. Adjunto pantallazos al respecto:

![image](https://github.com/alexay7/tfg/assets/102191690/fcada073-4b7a-4bf7-8b79-40bda114d903)
![image](https://github.com/alexay7/tfg/assets/102191690/84ce6aaf-0d20-49f6-95fb-f282003e93bf)

En otras aplicaciones como Jidoujisho este problema no está presente.

¿Podría mejorarse el sistema en el que el texto es copiado, por favor?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Lo revisaré, aceptado
