### ISSUE TITLE
Sugerencia: Advertencia previa a marcar como "leído"

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#168]
Buenos días,

me gustaría sugerir la opción de añadir un cartel de advertencia en el momento en el que marques una serie o volumen como "leído".
Ello ser´ñia útil en situaciones en las que se pulsa el botón por error (mi caso) y marca el volumen como leído sin más, sin advertencia de ningún tipo.

¿Sería posible añadir dicha advertencia cuando se pulse el botón, por favor?

Gracias.
Un salido ;-)

**Comment by alexay7** [comment]
Entiendo el argumento, pero generalizandolo esto haría que tenga que poner una advertencia en todos los botones que ejecuten alguna acción. Algún motivo para que "marcar como leído" sea especial?
