### ISSUE TITLE
Poder seleccionar varios volumenes a la vez para marcar como leido

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#18]
![image](https://github.com/alexay7/tfg/assets/119679067/2461b921-f753-4c2f-8bf6-1b97c34ef037)
En casos como esto que ya he leido todo antes, me gustaria poder darles leidos a todos de una forma más rapida.

**Comment by alexay7** [comment]
Cierto es, se acepta

**Comment by alexay7** [comment]
Solucionado en 16fb394258c0e59b52e1a0ee43e3053132e04b0a
