### ISSUE TITLE
Los libros que ya has leido que no aparezcan en libros nuevos

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#20]
![image](https://github.com/alexay7/tfg/assets/119679067/cdf54b6a-aa08-4931-a1c2-5d33ef2f9980)
Como se puede ver en esta imagen, me gustaria que no aparezcan los que ya leí.

**Comment by alexay7** [comment]
Eso molesta ahora porque la biblioteca es nueva, en esa sección aparecen los libros nuevos así que teóricamente no deberías haber podido leerlos
