### ISSUE TITLE
Tener un boto para copiar el log desde tu historial

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#21]
![image](https://github.com/alexay7/tfg/assets/119679067/381a24f7-76dc-44b8-b88b-45fd41d71c11)
Por ejemplo le das al boton copiar y te copia el log de esta forma:
.log manga [numero de paginas] [titulo de manga] [numero de volumen];[tiempo]&[numero de caracteres]

**Comment by alexay7** [comment]
No quiero relacionar mucho al bot con la web de momento pero lo apunto
