### ISSUE TITLE
Sugerencia: ⚠️ Advertencia ⚠️ informando que el volumen ya está leido y que vas a reiniciarlo..

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#23]
Buenas tardes,

¿podría añadirse un cartel informativo sobre una serie ya finalizada o un volumen ya acabado que aparezca advirtiendo al usuario de dicha finalización y si desea continuar?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
No entiendo bien, que cuando llegues al final de un libro te avise?

**Comment by TriDyE** [comment]
Buenas tardes,

perdón por no explicarme correctamente. Hacía referencia a volver a abrir un volumen o serie en estado "Leído", que aparezca un mensaje advirtiendo de ello, que ya está "Leído" y si quieres volver a empezarlo.

 El proceso que indico sería el siguiente:

1. Acabar un volumen / serie. Pasa a estado "Leído".
2. Volver a abrir dicho volumen / serie ya leído.
3. Actualmente no aparece nada. Se abre sin advertir nada. Aquí habría que añadir un cartel informativo advirtiendo que ya lo has leído y si quieres volver a leerlo.

¡Un saludo!

**Comment by alexay7** [comment]
Entendido, se aprueba
