### ISSUE TITLE
Imposibilidad pasar página o mostrar barras superior e inferior en Android

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#28]
Buenas tardes,

adjunto vídeo con el proceso para replicar el problema, el cual es no poder sacar las barras de progreso ni pasar página hasta actualizar la web:

https://github.com/alexay7/tfg/assets/102191690/12b15020-8f38-4329-81cc-9445b114c46b

El proceso es el siguiente:

1. Zoom&Pan activo
2. Quitar barras (doble toque espacio sin texto)
3. Abrir diccionario tocando cualquier línea de texto
4. Hacer zoom (con 2 dedos)
5. Abrir otra app
6. Volver a la web

Probablemente no tenga remedio si es cosa de Android...
Ocurre teniendo el diccionario abierto tras zoom. No he probado a hacerlo sin tener diccionario abierto.

Gracias por la atención.
Un saludo.

**Comment by alexay7** [comment]
He hecho exactamente los pasos en iOS y no me pasa, no tengo dispositivos android para probar, así que salvo que consigas un error de consola o algo con lo que pueda trabajar, tengo que dejar este bug como can't repo.
