### ISSUE TITLE
Ctrl para hacer zoom (PC): Funcionamiento inadecuado

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#31]
Buenos días,

si la opción dentro de un manga de "Ctrl para hacer zoom (PC)", está **desactivada**, puedes hacer zoom con Ctrl y la rueda del ratón sin problemas. **Es indiferente que esté activada la opción o no**.

La única opción que si varía el funcionamiento del zoom, es la opción de "Zoom&Pan".

¿Podría revisarse este asunto, por favor?

Gracias.
Un sal**i**do.

**Comment by alexay7** [comment]
La función está mal explicada, realmente lo que limita es la posibilidad de moverse por el visor del libro, pero el zoom no está limitado.

Tomo nota para cambiar el texto del ajuste pero no puedo hacer nada al respecto ya que es una función dentro del propio mokuro
