### ISSUE TITLE
Problema cronómetro: ocultar y mostrar las barras provoca que se anule la pausa

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#33]
Buenos días,

si el cronometro está PAUSADO, haces doble click para ocultar las barras y nuevamente doble click para mostrarlas, si consultas el cronometro este está ACTIVO cuando realmente debería estar pausado.

¿Podría revisarse este asunto, por favor?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Se acepta
