### ISSUE TITLE
Modo oscuro para el .html del mokuro si uno lo abre directamente

### ISSUE THREAD

**Issue by rotero08** [alexay7/tfg#35]
Está en modo claro, me duelen los ojos, creo que los perderé dentro de poco si sigo leyendo manga así.

![opera_GxX2DT7lru](https://github.com/alexay7/tfg/assets/45806562/c0169241-baf6-4264-b4bc-b1315fd2b6d3)

Lo quiero en modo oscuro así como lo hizo el de jidoujisho.

![image](https://github.com/alexay7/tfg/assets/45806562/1b5ed59a-90fe-4fe0-85dc-a1340a9332cc)

**Comment by alexay7** [comment]
En el caso de esa aplicación, el desarrollador puede modificar el aspecto del html ya que puede seguir inyectando código en el entorno de la app.

Sin embargo en el caso de la web, yo no puedo hacer cambios en el archivo html cuando lo cargais directamente del sistema de archivos así que no puedo modificar el color de fondo.

Solo podría hacerlo algo en aquellos libros donde se haya pasado la versión más nueva de mokuro con la posibilidad de cambiar el fondo.

**Comment by rotero08** [comment]
![image](https://github.com/alexay7/tfg/assets/45806562/b20ff016-67ef-4e9e-8758-5c4cba401b66)

Bueno entonces haz lo del mejor de los casos xD.

**Comment by alexay7** [comment]
Ok, se acepta
