### ISSUE TITLE
Mostrar qué es cada ícono al dejar el mouse encima

### ISSUE THREAD

**Issue by ElaxDev** [alexay7/tfg#39]
Creo que sería una buena adición al sitio ya que ayudaría en el ámbito de la usabilidad a saber qué es cada cosa.

Ejemplo de Github:
![image](https://github.com/alexay7/tfg/assets/31047609/873fae8b-d4ed-47fa-be7b-62e2f783e1c1)

**Comment by alexay7** [comment]
Se acepta
