### ISSUE TITLE
Sugerencia: Modificar aspecto botones "siguiente volumen" y "anterior volumen"

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#40]
Buenos días,

me gustaría solicitar el modificar el actual aspecto de los botones del asunto, ya que habitualmente los confundo con adelantar o atrasar 1 única página y su utilidad real no es cambio de página, si no cambio de volumen.

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Se acepta
