### ISSUE TITLE
Sugerencia: Añadir registros en el historial que superen X segundos

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#41]
Buenos días,

desconozco si es posible, pero me gustaría solicitar que los registros menores de X segundos no queden reflejados en el historial. 
Por ejemplo, cuando por error cambio de volumen en lugar de página o abro un manga por error en lugar del menú de información, los 2 o 3 segundos que tardo en darme cuenta y volver al punto anterior, quedan reflejados en el historial de la web.

Sería incluir únicamente los que superen dichos X segundos, por ejemplo 10 o 20.

Gracias.
Un saludo.

**Comment by alexay7** [comment]
En ese caso creo que lo mejor sería borrar los registros que, como dices, has abierto por error.
