### ISSUE TITLE
Añadir sugerencias de volúmenes o series a incluir en la Biblioteca

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#42]
Buenos días,

¿sería posible añadir una sección donde los usuarios podamos realizar sugerencias para incluir nuevos tomos o series completas a YomiYasu?

Un buen ejemplo de formulario o sección, es el que usa Learn Natively.

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Por ahora quiero que la biblioteca sea gestión única del administrador de cada instancia de yomiyasu sin colaboración externa. Lo cierro por ahora pero tomo nota para el futuro.
