### ISSUE TITLE
Botón "leer más" y "leer menos" dentro de una serie

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#43]
Buenos días,

La función de ambos botones dentro de una serie es mostrar el texto adicional sobre dicha serie o ocultar texto adicional, para que entre todo comodamente en pantalla.

Sin embargo, si no hay más texto que mostrar ni ocultar, si no que simplemente pulsar dichos botones no varía nada, sería una interesante opción el que dichos botones no aparezcan si no hay más texto disponible.

Antes:de pulsar el botón:
![image](https://github.com/alexay7/tfg/assets/102191690/7beeb949-42a7-44d8-9a2c-98888d73c4dc)

Tras pulsarlo:
![image](https://github.com/alexay7/tfg/assets/102191690/2453a01a-cc18-4979-ab34-a4379a68fd88)

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Se acepta
