### ISSUE TITLE
Suggestion: Save filter configuration in history for later use

### ISSUE THREAD

**Issue by SirGram** [alexay7/tfg#50]
![image](https://github.com/alexay7/tfg/assets/119138378/45ff4a33-ef96-4e21-8b70-ca70f72fe169)

**Comment by alexay7** [comment]
そういう表は外部ライブラリのもののため、あまりに変わることはできません。

**Comment by SirGram** [comment]
Would it be possible to show first instead of last the latest volume you've read by default?

**Comment by alexay7** [comment]
それなら大丈夫です。承認
