### ISSUE TITLE
Suggestion: show remaining characters instead of full length in progress tab

### ISSUE THREAD

**Issue by SirGram** [alexay7/tfg#51]
![image](https://github.com/alexay7/tfg/assets/119138378/2a15de4a-355b-4d19-9792-5a553f0c1836)
4000 instead of 8000+

**Comment by alexay7** [comment]
承認

**Comment by SirGram** [comment]
Remaining time not showing correctly
![image](https://github.com/alexay7/tfg/assets/119138378/fc7c8f10-612d-4946-a825-f8e9ab097191)
![image](https://github.com/alexay7/tfg/assets/119138378/c89be917-6d12-4ba3-afba-02d38df14978)
