### ISSUE TITLE
Sugerencia: botón volver atrás en menú crear carta 

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#52]
Buenos días,

actualmente el menú de crear carta, no dispone de un menú para volver atrás sin crear nada.
¿Podría implementarse un botón para ello, por favor?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
El menú de crear carta está pensado para ser un popup en pc y una ventana nueva en navegador móvil, no procede un botón de volver atrás porque es un menú separado de la web.

Si no te crear el popup/ventana nueva ya estaríamos hablando de un fallo o de estar usando un navegador sin posibilidad de tener varias pestañas.

**Comment by TriDyE** [comment]
Disculpa de antemano.
No me había fijado que efectivamente se abría en otra pestaña. Cerrar dicha pestaña es equivalente a lo que solicito, por lo que cierro ticket.

Gracias por la atención.
