### ISSUE TITLE
Bug: se muestra diccionario nativo aún desactivado

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#54]
Buenos días,

si el diccionario nativo está desactivado, cuando se abre el menú del cronómetro y se pulsa sobre el tiempo, aparece el diccionario nativo mostrando あれ.
No debería aparecer nada si está desactivado y menos pinchando sobre el tiempo del cronómetro.

¿Puede revisarse este asunto, por favor?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
He intentado replicarlo tanto en pc como en móvil y no me ha pasado, puedes mandar vídeo?

**Comment by TriDyE** [comment]
https://github.com/alexay7/tfg/assets/102191690/7f30464d-bcc7-4f65-af85-0c9dc5f05ca8

**Comment by alexay7** [comment]
lo conseguí replicar, aceptado
