### ISSUE TITLE
Add option to search by author

### ISSUE THREAD

**Issue by SirGram** [alexay7/tfg#65]
![image](https://github.com/alexay7/tfg/assets/119138378/6ff0d8eb-f09f-433a-af9a-c6dceb04423f)

**Comment by alexay7** [comment]
![image](https://github.com/alexay7/tfg/assets/43906716/f78d97e8-14f2-4d65-9a65-0ad7d1d76052)

そんなようなフィルターもうありますよ、ローマ字は受けないなだけ。
