### ISSUE TITLE
Sugerencia: pausar o reanudar cronómetro con tecla espacio en teclado (PC)

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#95]
Buenas tardes;

¿existiría posibilida de parar o reanudar el crono utilizando una tecla del teclado (espacio)?
Actualmente es posible alternar páginas utilizando las flechas laterales, pero desconozco si sería posible pausar o reanudar el crono también usando otra tecla.

Yo, que atiendo al público y consultas random de empleados, me resultaría extremadamente útil poder parar y reanudar el crono rápidamente pulsando una tecla. 

Gracias.
Un saludo.

**Comment by alexay7** [comment]
La tecla espacio está reservada a cambiar de página pero si tengo pensado hacer keybinds.

**Comment by alexay7** [comment]
Se mueve a #102
