### ISSUE TITLE
Problema zoom al pasar de página: ajuste vertical

### ISSUE THREAD

**Issue by TriDyE** [alexay7/tfg#96]
Buenas tardes,

cuando la opción del asunto está configurada, al pasar de página, si las barras superior e inferior de progreso están visibles, el zoom no se ajusta correctamente, en ocasiones tapando viñetas con texto. Es indiferente el que estén las barras superior e inferior visibles, siempre se ajusta el zoom al alto de la pantalla como si dichas barras no estuvieran visibles.

¿Podría ajustarse para que cuando ambas barras esten visibles, el zoom vertical se adapte a ellas y no quede la página parcialmente por debajo de dichas barras, por favor?

Gracias.
Un saludo.

**Comment by alexay7** [comment]
Hacer eso requeriría que cada vez que quites y pongas las barras, se tenga que recalcular el alto del lector.

El objetivo de las barras es ser algo orientativo para tenerlo visible cuando lo necesites y no algo que esté presente siempre mientas lees el manga, por ello, veo adecuado que cubra una parte del lector para incentivar a su ocultamiento.

**Comment by TriDyE** [comment]
¡Entendido!
