### ISSUE TITLE
Ordernar "Tu Tablero" por la serie mas reciente que hayas leido

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#97]
![image](https://github.com/alexay7/tfg/assets/119679067/adc88296-4ba1-479f-8e15-90040e7ad3ca)
Seria bueno que **Tu Tablero** este ordernado por tu lectura mas reciente.

**Comment by alexay7** [comment]
Complicado por la arquitectura de los progresos pero veré si puedo hacer algo
