### ISSUE TITLE
Atajo de teclado para "doble pagina" y "Primera pagina es caratula"

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/tfg#99]
Para doble pagina seria d y para Primera pagina es caratula seria c.
Quiero esto porque a veces el manga acaba antes y el atogaki esta al costado de el ultimo panel. Y no quiero logear los caracteres de el atogaki. Por eso quiero el atajo de doble pagina o al menos el de primera pagina es caratula que es el mas versatil.

**Comment by alexay7** [comment]
Se mueve a #102
